### ISSUE TITLE
[WIP]: Add more questions

### ISSUE THREAD

**Issue by gabrielmocanu** [mariasfiraiala/SO-exam#10]
If anyone wants to add the questions from this [document], It's more than welcome.
I think this document dates back to when @teodutu, @craciunoiuc  and I were still young and restless, so it also contains questions from the old SO material.

[document]: https://docs.google.com/document/d/1UPE6mVZ6fT3I8RYCs_UDzRSUAtqj-COQ3WTzjnBkPbc/edit#heading=h.k3b5pwbbz5kv

**Comment by teodutu** [comment]
Brings back memories :smiling_face_with_tear:.

**Comment by mariasfiraiala** [comment]
> If anyone wants to add the questions from this [document](https://docs.google.com/document/d/1UPE6mVZ6fT3I8RYCs_UDzRSUAtqj-COQ3WTzjnBkPbc/edit#heading=h.k3b5pwbbz5kv), It's more than welcome. I think this document dates back to when @teodutu, @craciunoiuc and I were still young and restless, so it also contains questions from the old SO material.

We'll take care of that don't you worry.
We'll keep this issue open in order for students to word their ides here.

**Comment by mariasfiraiala** [comment]
For starters, I've added all the old questions that weren't part of the ones already upstream  (640118c). I'll start answering them soon.
If anyone fancies doing some more research (popular topics: security and file systems), you're welcomed to begin, I hope we won't have too many merge conflicts :blush:

**Comment by mariasfiraiala** [comment]
Closed via 7280b51.
