### ISSUE TITLE
software stack: students are obsessed with this answer

### ISSUE THREAD

**Issue by razvanvirtan** [mariasfiraiala/SO-exam#12]
I suggest designing [this](https://github.com/mariasfiraiala/SO-exam/blob/master/software-stack/software-stack-q%26a.md?plain=1#L88) into a less attractive phrase, that won't become such a hit during the exams (and can't be associated with OOP course ;) ).

**Comment by mariasfiraiala** [comment]
Thanks @razvanvirtan! Indeed, the answer can be wrongly interpreted. What do you think about "O bibliotecă este o colecție de fișiere obiect"?

**Comment by razvanvirtan** [comment]
Sounds good 👍
