### ISSUE TITLE
Make question body distinctive from the answer

### ISSUE THREAD

**Issue by mariasfiraiala** [mariasfiraiala/SO-exam#6]
This issue discusses different modalities of highlighting the question body from the answer, without giving up the question numbering.

GitHub Markdown doesn't support colored text but  a few alternatives are:

* using colored emojis before and after the question body (counterintuitive and ugly)

* using diff syntax (inelegant and hard to use with line numbering):

   ```diff
   + something 
   ```

   ```diff
   @@ something @@
   ```

  ```diff
  - something
  ```

* use bold

If you're interested, share your ideas and if you'd like to pick up this issue and work on it, let's first come to a conclusion here.

**Comment by corneliu-rotari** [comment]
Try to add the question body as a heading, excluding the numbering, the downside is that the number is to small
1. ## Question?

**Comment by mariasfiraiala** [comment]
> Try to add the question body as a heading, excluding the numbering, the downside is that the number is to small `1. ## Question?`

I am hesitant to go with this approach exactly because of the difference in size between the number and the question body.

**Comment by RaduNichita** [comment]
What do you think about using [this format](https://github.com/AlessandroCorradini/University-of-California-San-Diego-Big-Data-Specialization/blob/master/01%20-%20Introduction%20to%20Big%20Data/Quiz%201%20-%20Why%20Big%20Data%20and%20Where%20Did%20it%20Come%20From.md)?

**Comment by corneliu-rotari** [comment]
> What do you think about using [this format](https://github.com/AlessandroCorradini/University-of-California-San-Diego-Big-Data-Specialization/blob/master/01%20-%20Introduction%20to%20Big%20Data/Quiz%201%20-%20Why%20Big%20Data%20and%20Where%20Did%20it%20Come%20From.md)?

That will mean to renumber every question in every document. It the format is okay i can easily refactor it.

**Comment by mariasfiraiala** [comment]
Ok then, let's do it this way. I still believe it looks kind of ugly (Markdown wise), but we'll change it afterwards, if we find a better approach. 

@corneliu-rotari Please take care of it, I'll assign this issue to you. Thanks a lot!
